### ISSUE TITLE
v11 - Replace canvas.app.renderer.plugins.interaction.mouse

### ISSUE THREAD

**Issue by MaxPat931** [manuelVo/foundryvtt-rangefinder#6]
I was able to get this working with a change to `src/main.js` based on these comments I found on the Foundry discord re: canvas.app.renderer.plugins.interaction.mouse  https://discord.com/channels/170995199584108546/811676497965613117/1117464080253456474

Replace lines 104 and below with:
```js
function measure(event) {
	const ruler = canvas.controls.ruler
	canvas.app.stage.on("pointermove", event => {
		const canvasMousePos = event.getLocalPosition(canvas.app.stage);

		const mt = ruler.rangefinderMeasureTime ?? 0

		// Hide any existing Token HUD
		canvas.hud.token.clear();

		// Draw measurement updates
		if ( Date.now() - mt > 50 ) {
		ruler.measure(canvasMousePos, {gridSpaces: !event.shiftKey});
		ruler.rangefinderMeasureTime = Date.now();
		ruler._state = Ruler.STATES.MEASURING;
		}
	})
}
```

**Comment by LukasPrism** [comment]
Thanks for this!

I still wonder if this couldn’t just be a feature of Drag Ruler then we could retire this module 🤔

**Comment by manuelVo** [comment]
@MaxPat931 thanks for the suggestion. I've updated the module for v11, albeit slightly differently.

@LukasPrism I honestly don't see any benefit of merging the two modules into one. On the contrary, I can imagine such a merge to hurt some users. The user base of Rangefinder is not the same as the user base of Drag Ruler - merging the modules would force people who only need the features of one of the modules to install the features of the other module as well. Range finder is a super-lightweight module that is unlikely to cause any conflicts to other modules or to break due to a Foundry update (in fact, this is the first time the module broke due to a Foundry update since it's inception in Foundry 0.7). Contrast this with Drag Ruler, which is a beast of a module, which has lots of opportunities to cause trouble in combination with other modules and is - due to it's size - basically guaranteed to break in some way with every major release of foundry. Forcing the compatibility risk that is Drag Ruler onto users that would be fine using only the Feature Rangefinder provide would massively hurt those users.

**Comment by MaxPat931** [comment]
Awesome, thanks for the update!

**Comment by LukasPrism** [comment]
@manuelVo Totally understand and thanks for the update! Really appreciate it.
Sorry I may have not been clear, I meant if Drag Ruler had this feature we also wouldn't need Rangefinder installed. I didn't mean you should let this module die and inconvenience those who don't use Drag Ruler. But I have no issue with having both installed!
Cheers

**Comment by manuelVo** [comment]
@LukasPrism Doing so would require me to maintain the same functionality twice, which I will certainly not do ;)
